from PIL import Image

from lasergrbl_macos.gcode import RasterSettings, image_to_gcode, parse_motion_segments


def test_parses_absolute_and_relative_motion() -> None:
    segments = parse_motion_segments(
        """
        G21 G90
        M4 S200
        G1 X10 Y5
        G91
        G0 X-2
        M5
        G1 Y3
        """
    )

    assert len(segments) == 3
    assert segments[0].start == (0.0, 0.0)
    assert segments[0].end == (10.0, 5.0)
    assert segments[0].power == 200
    assert segments[1].end == (8.0, 5.0)
    assert segments[1].rapid
    assert segments[2].end == (8.0, 8.0)
    assert segments[2].power == 0


def test_converts_inch_coordinates_to_millimeters() -> None:
    segments = parse_motion_segments("G20 G90 G0 X1 Y0.5")

    assert segments[0].end == (25.4, 12.7)


def test_generates_bounded_serpentine_raster() -> None:
    image = Image.new("L", (2, 2))
    image.putdata([0, 255, 128, 0])
    settings = RasterSettings(
        width_mm=2,
        height_mm=2,
        pixels_per_mm=1,
        threshold=200,
        maximum_power=1_000,
        feed_rate=800,
    )

    commands = image_to_gcode(image, settings)

    assert commands[:6] == [
        "; Generated by LaserGRBL for macOS",
        "G21",
        "G90",
        "G17",
        "F800",
        "M4 S0",
    ]
    assert "G0 X0.000 Y2.000 S0" in commands
    assert "G0 X2.000 Y0.000 S0" in commands
    assert "G1 X0.000 S1000" in commands
    assert commands[-3:] == ["M5", "G0 X0 Y0", "; End of job"]


def test_rejects_excessive_raster_size() -> None:
    image = Image.new("L", (1, 1), 0)
    settings = RasterSettings(width_mm=100, height_mm=100, pixels_per_mm=10, maximum_points=10_000)

    try:
        image_to_gcode(image, settings)
    except ValueError as error:
        assert "safety limit" in str(error)
    else:
        raise AssertionError("Expected an oversized raster to be rejected")
