from __future__ import annotations

import re
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

from PIL import Image

from .grbl import clean_gcode_line

WORD_PATTERN = re.compile(r"([A-Z])\s*([-+]?(?:\d+(?:\.\d*)?|\.\d+))", re.IGNORECASE)


@dataclass(frozen=True, slots=True)
class RasterSettings:
    width_mm: float
    height_mm: float
    pixels_per_mm: int = 3
    threshold: int = 220
    maximum_power: int = 1_000
    feed_rate: int = 1_000
    maximum_points: int = 400_000

    def validate(self) -> None:
        if not 0 < self.width_mm <= 1_000 or not 0 < self.height_mm <= 1_000:
            raise ValueError("Artwork dimensions must be between 0 and 1,000 mm.")
        if not 1 <= self.pixels_per_mm <= 20:
            raise ValueError("Resolution must be between 1 and 20 pixels per millimeter.")
        if not 0 <= self.threshold <= 255:
            raise ValueError("Threshold must be between 0 and 255.")
        if not 1 <= self.maximum_power <= 10_000:
            raise ValueError("Maximum laser power must be positive.")
        if not 1 <= self.feed_rate <= 100_000:
            raise ValueError("Feed rate must be positive.")


@dataclass(frozen=True, slots=True)
class MotionSegment:
    start: tuple[float, float]
    end: tuple[float, float]
    rapid: bool
    power: float


def _laser_power(intensity: int, settings: RasterSettings) -> int:
    if settings.threshold == 0 or intensity >= settings.threshold:
        return 0
    ratio = (settings.threshold - intensity) / settings.threshold
    return max(1, round(settings.maximum_power * ratio))


def image_to_gcode(image_source: str | Path | Image.Image, settings: RasterSettings) -> list[str]:
    settings.validate()
    width_pixels = max(2, round(settings.width_mm * settings.pixels_per_mm))
    height_pixels = max(2, round(settings.height_mm * settings.pixels_per_mm))
    point_count = width_pixels * height_pixels
    if point_count > settings.maximum_points:
        raise ValueError(
            f"The selected size and resolution produce {point_count:,} points; "
            f"the safety limit is {settings.maximum_points:,}."
        )

    should_close = not isinstance(image_source, Image.Image)
    image = Image.open(image_source) if should_close else image_source
    try:
        grayscale = image.convert("L").resize(
            (width_pixels, height_pixels),
            Image.Resampling.LANCZOS,
        )
    finally:
        if should_close:
            image.close()

    commands = [
        "; Generated by LaserGRBL for macOS",
        "G21",
        "G90",
        "G17",
        f"F{settings.feed_rate}",
        "M4 S0",
    ]

    for row in range(height_pixels):
        columns: Iterable[int]
        if row % 2 == 0:
            columns = range(width_pixels)
        else:
            columns = range(width_pixels - 1, -1, -1)

        y_position = settings.height_mm * (height_pixels - 1 - row) / (height_pixels - 1)
        ordered_columns = list(columns)
        first_column = ordered_columns[0]
        first_x = settings.width_mm * first_column / (width_pixels - 1)
        commands.append(f"G0 X{first_x:.3f} Y{y_position:.3f} S0")

        for column in ordered_columns:
            x_position = settings.width_mm * column / (width_pixels - 1)
            power = _laser_power(grayscale.getpixel((column, row)), settings)
            commands.append(f"G1 X{x_position:.3f} S{power}")

    commands.extend(["M5", "G0 X0 Y0", "; End of job"])
    return commands


def parse_motion_segments(source: str | Iterable[str]) -> list[MotionSegment]:
    lines = source.splitlines() if isinstance(source, str) else source
    absolute_positioning = True
    unit_scale = 1.0
    motion_mode: int | None = None
    laser_enabled = False
    spindle_power = 0.0
    current_x = 0.0
    current_y = 0.0
    segments: list[MotionSegment] = []

    for raw_line in lines:
        line = clean_gcode_line(raw_line).upper()
        if not line:
            continue
        words = [(letter.upper(), float(value)) for letter, value in WORD_PATTERN.findall(line)]
        if not words:
            continue

        for letter, value in words:
            if letter == "G":
                code = int(value)
                if code == 20:
                    unit_scale = 25.4
                elif code == 21:
                    unit_scale = 1.0
                elif code == 90:
                    absolute_positioning = True
                elif code == 91:
                    absolute_positioning = False
                elif code in {0, 1}:
                    motion_mode = code
            elif letter == "M":
                code = int(value)
                if code in {3, 4}:
                    laser_enabled = True
                elif code == 5:
                    laser_enabled = False
            elif letter == "S":
                spindle_power = max(0.0, value)

        x_value = next((value for letter, value in words if letter == "X"), None)
        y_value = next((value for letter, value in words if letter == "Y"), None)
        if motion_mode not in {0, 1} or (x_value is None and y_value is None):
            continue

        target_x = current_x
        target_y = current_y
        if x_value is not None:
            scaled_x = x_value * unit_scale
            target_x = scaled_x if absolute_positioning else current_x + scaled_x
        if y_value is not None:
            scaled_y = y_value * unit_scale
            target_y = scaled_y if absolute_positioning else current_y + scaled_y

        if (target_x, target_y) != (current_x, current_y):
            rapid = motion_mode == 0
            segments.append(
                MotionSegment(
                    start=(current_x, current_y),
                    end=(target_x, target_y),
                    rapid=rapid,
                    power=spindle_power if laser_enabled and not rapid else 0.0,
                )
            )
        current_x, current_y = target_x, target_y

    return segments
